version: "3.9"
services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./php/:/var/www/html
    depends_on:
      - php

  php:
    build: ./php/
    expose:
      - "9000"
    volumes:
      - ./php/:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: kasir
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
